baseURL: "https://soulvai.github.io/"
title: Roman Bin Alam
theme: "PaperMod"

params:
  defaultTheme: auto # This creates the sun/moon toggle at the top!
  ShowReadingTime: true
  ShowShareButtons: true

menu:
  main:
    - name: Paper Reading
      url: /categories/reading/
      weight: 1
    - name: Replications
      url: /categories/replications/
      weight: 2
    - name: Hands_on
      url: /categories/hands_on/
      weight: 3
    - name: Unfiltered
      url: /categories/unfiltered/
      weight: 4
